GuiaBolso/pink-lemonade-web

package-lock.json

chore: 🤖 update dependences

---

package-lock.json

Reverts GuiaBolso/pink-lemonade-web#5

Revert "chore: 🤖 update dependences"

---

.github/workflows/master.yml
.github/workflows/pull_request.yml
libs/ui/CHANGELOG.md
libs/ui/src/typings/fonts.d.ts
package-lock.json

chore: 🤖 clean cache

---

.github/workflows/master.yml
.github/workflows/pull_request.yml
libs/ui/src/typings/fonts.d.ts
package-lock.json
package.json

chore: 🤖 clean cache master

---

.github/workflows/master.yml
.github/workflows/pull_request.yml
libs/ui/src/lib/notification/Modal/Modal.context.tsx
package-lock.json
package.json

fix: :bug: uuid

---

libs/ui/src/lib/notification/Modal/Modal.context.tsx
libs/ui/src/lib/notification/Toast/Toast.context.tsx
libs/ui/src/lib/notification/Toast/Toast.stories.tsx
package-lock.json
package.json

Mil tretas do GitHub Actions com o uuid

feat: remove uuid add uniqid

---

libs/ui/src/lib/forms/Button/Button.style.tsx
libs/ui/src/lib/notification/Modal/Modal.tsx
libs/utils/src/lib/hooks/create-store-hooks/create-store-hooks.tsx

retirando narrow da propriedade do botão do material ui

fix: 🐛 remove props bolean from dom

---

libs/ui/src/lib/notification/Modal/Modal.tsx

fix: 🐛 cancel subscribe

---

libs/ui/src/lib/notification/Modal/Modal.tsx
libs/ui/src/lib/notification/Toast/Toast.container.tsx
libs/ui/src/lib/notification/Toast/Toast.style.ts
libs/ui/src/lib/notification/Toast/Toast.tsx

- Ajuste no `z-index`
- Ajuste no responsivo
- Adição de classes css para customização adicional pelo lado do cliente

style: 💄 z-index and mobile improvment

---

libs/ui/src/lib/notification/Modal/Modal.container.tsx

fix: 🐛 remove modal from portal

---

.eslintrc
.vscode/extensions.json
.vscode/settings.json
libs/ui/CHANGELOG.md
libs/ui/package.json
libs/ui/src/lib/notification/Toast/Toast.tsx
libs/utils/CHANGELOG.md
libs/utils/package.json

Fiz umas melhorias no nosso eslint removendo alguns plugins desnecessários e melhorando a integração com o prettier.

style: 💄 melhorias no eslint

---

libs/ui/.storybook/webpack.config.js
libs/ui/CHANGELOG.md
libs/ui/package.json
libs/utils/CHANGELOG.md
libs/utils/package.json

o plugin docgen começou a apresentar um erro incapacitando a reproduçao
do storybook. Existe uma issue que foi aberta aos desenvoledores para
arrumar o erro:
https://github.com/strothj/react-docgen-typescript-loader/issues/107

fix: 🐛 docgen error

---

.github/workflows/master.yml
build-storybook.log
libs/ui/CHANGELOG.md
libs/ui/package.json
libs/ui/src/lib/notification/Modal/Alert.stories.mdx
package-lock.json
package.json
workspace.json

Teste de publicação do storybook no chromatic
https://5f1f22ccab17b9002215a487-nuqxqwohoi.chromatic.com/

chore: 🤖 add chromatic to public storybook

---

.github/workflows/master.yml
package.json

Adicionado flag para finalizar quando o upload for completo no nosso ci do storybook

chore: 🤖 add flag to exit on publish storybook

---

libs/ui/src/lib/navigation/DropMenu/DropMenu.style.ts
libs/ui/src/lib/navigation/DropMenu/DropMenu.tsx

Alguns ajustes e melhorias para o melhor comportamento do componente onde ele será utilizado.

fix: 🐛 some types and properties needed

---

libs/ui/src/lib/display/Text/Text.style.ts
libs/ui/src/lib/display/Tooltip/Tooltip.stories.tsx
libs/ui/src/lib/display/Tooltip/Tooltip.style.tsx
libs/ui/src/lib/display/Tooltip/Tooltip.tsx
libs/ui/src/lib/notification/infoPanel/__snapshots__/InfoPanel.test.tsx.snap

Adicionei a prop `title` no Tooltip conforme especificado no [Design System].
Tambem adicionei passei duas props pro Tooltip do MaterialUi para que o seja esperado o comportamento de click no mobile. 
```
enterTouchDelay={1}
leaveTouchDelay={1}
```

style: 💄 Adding title at Tooltip component

---

libs/ui/src/lib/display/Tooltip/Tooltip.stories.tsx

Adicionei uma nova storie no Tooltip, unicamente pra possibilitar a geração do package pro npm.

feat: 🎸 Adding new story in Tooltip

---

libs/ui/src/lib/notification/infoBanner/InfoBanner.style.ts

O componente InfoBanner estava sem z-index fazendo se comportar de maneira errada.
Foi adicionado um zindex.

fix: zindex missing

---

libs/ui/src/lib/display/Text/Text.tsx

O ideal é que possamos acessar os tipos de variant separado do componente, pensando que poderá ser passado via prop.

feat: 🎸 Export variant types

---

libs/utils/src/lib/ab-test/ab-test.spec.ts
libs/utils/src/lib/ab-test/ab-test.ts

adicionei o sessionToken no helper de teste ab

feat: 🎸 add sessionStorage in ab test helper

---

libs/ui/src/assets/images/icons/alert.svg
libs/ui/src/lib/notification/ProgressBar/ProgressBar.stories.tsx
libs/ui/src/lib/notification/ProgressBar/ProgressBar.style.ts
libs/ui/src/lib/notification/ProgressBar/ProgressBar.tsx

Esse componente não estava podendo ser muito customizado, e surgiu a demanda pelo time de UX de colocar um icone diferente em casos de erro.
Foram adicionada duas props:
* `hasError` é uma flag que quando ativa mostra um icone de erro específico
* `customIcon` recebe um componente react e exibe ele no lugar do icone.
**No caso de mudança de layout, como estava antes e qual a mudança esperada?**
|    Layout ANTES da alteração    |    Layout DEPOIS da alteração    |
| :-----------------------------: | …

Novas props para o componente ProgressBar

---

libs/ui/src/lib/navigation/Accordion/Accordion.stories.tsx
libs/ui/src/lib/navigation/Accordion/Accordion.tsx
libs/ui/src/lib/navigation/Accordion/__snapshots__/Accordion.spec.tsx.snap

**No caso de mudança de layout, como estava antes e qual a mudança esperada?**
|    Layout ANTES da alteração    |    Layout DEPOIS da alteração    |
| :-----------------------------: | :------------------------------: |
| ![Layout ANTES](#URL_DA-IMAGEM) | ![Layout DEPOIS](#URL_DA-IMAGEM) |
**No caso de refactoring, houve adição/remoção de código? (Além da mudança do código de lugar)**
**Como posso testar isso?**
**Quais componentes devem ser checados no Story Book?**
**Mais informações úteis?**

refactor: 💡 (wip) expand one panel at a time

---

libs/ui/src/lib/navigation/Accordion/Accordion.tsx

O accordion estava com um bugzinho em que não fechava o panel ao clicar novamente.

fix: 🐛 accordion single expand behavior

---

libs/ui/src/lib/forms/Select/Select.spec.tsx
libs/ui/src/lib/forms/Select/Select.stories.tsx
libs/ui/src/lib/forms/Select/Select.style.tsx
libs/ui/src/lib/forms/Select/Select.tsx
libs/ui/src/lib/forms/Select/__snapshots__/Select.spec.tsx.snap
libs/ui/src/lib/icons/Close.tsx
libs/ui/src/lib/navigation/DropMenu/DropMenu.style.ts

- <a href="https://guiabolso.atlassian.net/browse/GBCONNECT-960" target="_BLANK">Link dessa tarefa no Jira</a>
Add select component

Adding select component

---

libs/ui/src/index.ts
libs/ui/src/lib/forms/Select/index.ts
libs/ui/src/lib/forms/index.ts

Havia esquecido de exportar os componentes `Select` e `Toggle`.

fix: 🐛 Export Select and Toggle component

---

libs/ui/src/lib/display/Tooltip/Tooltip.tsx

O componente não estava recebendo props.
No meu caso, quando fui testar o componente não foi possível passar o data-testid e não havia outra forma de pegar o elemento.

Add props to the Tooltip component

---

libs/ui/CHANGELOG.md
libs/ui/package.json
libs/utils/CHANGELOG.md
libs/utils/package.json
libs/utils/src/index.ts
libs/utils/src/lib/emotion-query/conversor.js
libs/utils/src/lib/emotion-query/index.js

**Descrição**
Nessa PR estamos colocando uma lib vendor que temos no Alfar para ficar disponível aqui. É uma lib para facilitar o uso de media query.

Adicionando emotion query

---

libs/ui/src/lib/notification/infoPanel/InfoPanel.stories.tsx
libs/ui/src/lib/notification/infoPanel/InfoPanel.style.ts
libs/ui/src/lib/notification/infoPanel/InfoPanel.tsx

Precisavamos que o componente Infopanel tivesse cores diferentes de background seguindo a paletta de cores do PinkLemonade.
Foi adicionado uma prop para passar o tipo de notificação e com isso mudar a cor do background.
**No caso de mudança de layout, como estava antes e qual a mudança esperada?**
Não houve mudança de layout
**No caso de refactoring, houve adição/remoção de código? (Além da mudança do código de lugar)**
**Como posso testar isso?**
Storybook
**Quais componentes devem ser checados no Story …

Infopanel Background color

---

libs/ui/src/@types/emotion.d.ts

**No caso de mudança de layout, como estava antes e qual a mudança esperada?**
|    Layout ANTES da alteração    |    Layout DEPOIS da alteração    |
| :-----------------------------: | :------------------------------: |
| ![Layout ANTES](#URL_DA-IMAGEM) | ![Layout DEPOIS](#URL_DA-IMAGEM) |
**No caso de refactoring, houve adição/remoção de código? (Além da mudança do código de lugar)**
**Como posso testar isso?**
**Quais componentes devem ser checados no Story Book?**
**Mais informações úteis?**

feat: 🎸 update ui version

---

libs/utils/src/lib/storage/storage.ts

fix: 🐛 check window

---

libs/utils/src/index.ts
libs/utils/src/lib/hooks/use-breakpoints/use-breakpoints.tsx
libs/utils/src/lib/hooks/use-media-query/use-media-query.tsx

- adicionado hook `useMediaQuery`
- adicionado hooj `useBreakpoints`

feat: 🎸 add useBreakpoints hook

---

libs/ui/src/index.ts

feat: 🎸 export icons

---

libs/ui/src/lib/containers/Card/Card.tsx

passando rest props para o componente Card

fix: 🐛 pass props to card

---

libs/ui/CHANGELOG.md
libs/ui/package.json
libs/ui/src/lib/forms/Checkbox/Checkbox.stories.tsx
libs/ui/src/lib/forms/Checkbox/Checkbox.style.ts
libs/ui/src/lib/forms/Checkbox/__snapshots__/Checkbox.spec.tsx.snap
libs/ui/src/lib/forms/Select/Select.style.tsx
libs/ui/src/lib/forms/Toggle/Toggle.style.ts
libs/ui/src/lib/forms/Toggle/__snapshots__/Toggle.spec.tsx.snap
libs/utils/CHANGELOG.md
libs/utils/package.json
package-lock.json
package.json

**Descrição**
Nessa PR estamos atualizando deps do material ui e arrumando alguns estilos que estava quebrado.

fix: 🐛 update deps

---

libs/ui/src/lib/forms/Button/Button.style.tsx
libs/ui/src/lib/notification/Modal/Modal.style.ts
libs/ui/src/lib/notification/Modal/Modal.tsx

mudança de layout dos botões do modal

feat: 🎸 change layout of modal footer

---

libs/ui/src/lib/forms/Button/Button.style.tsx

fix: 🐛 border button

---

libs/ui/src/lib/navigation/DropMenu/DropMenu.tsx

Precisamos de uma forma acessível de acessar o back-drop para poder fechar o menu.
Esse ajuste ajuda nos testes do `testing-library`
Adicionado role no back-drop e aria-label para identificação.

Style / Drop Menu backdrop WAI-ARIA attributes

---

libs/ui/CHANGELOG.md
libs/ui/package.json
libs/utils/CHANGELOG.md
libs/utils/package.json
package-lock.json
yarn.lock

A última PR não subiu a release pois não foi mantido o padrão de commit.
Esta PR atualiza as dependências apenas para abrir PR e rodar o fluxo novamente

Chore / update dependencies
